version: '3.8'

services:
  frontend:
    container_name: nuxt
    build: ./frontend
    volumes:
       # ホスト:コンテナ
      - ./frontend:/src
      - node_modules:/src/node_modules
    working_dir: "/src"
    ports:
      # ホスト:コンテナ
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true

    command: >
      sh -c '
        yarn install
        yarn dev
      '

    

volumes:
  node_modules: